[project]
name = "ai-product-hack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kekwak", email = "kekwak@mail.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
]

[project.scripts]
dataset-generate = "generate_dataset:main"
dataset-validate = "validate_dataset:main"
evaluate-predictions = "evaluate_predictions:main"

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["paths", "generate_dataset", "validate_dataset", "evaluate_predictions"]
