# Generated by Django 5.1.15 on 2026-09-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Текст заголовка, например 'Описание' или 'Установка'.", max_length=255)),
                ('level', models.PositiveSmallIntegerField(blank=True, choices=[(1, "H1 ('#')"), (2, "H2 ('##')"), (3, "H3 ('###')"), (4, "H4 ('####')"), (5, "H5 ('#####')"), (6, "H6 ('######')")], help_text='Уровень заголовка (# = 1 ... ###### = 6). Оставьте пустым, чтобы уровень не проверялся.', null=True)),
                ('is_required', models.BooleanField(default=True, help_text='Если выключено, заголовок необязателен и будет только проверен для информации.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения/проверки правил.')),
                ('is_active', models.BooleanField(default=True, help_text='Выключенные правила не участвуют в проверке.')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
